#!/usr/bin/python

import os

# Make sure aptitude version numbers etc don't use translations.
os.environ['LANG'] = 'C'

out = os.fdopen(3, 'w')

if 'TERM' in os.environ:
    out.write('Terminal: %s\n' % os.environ['TERM'])
else:
    out.write('$TERM not set.\n')

if 'DISPLAY' in os.environ:
    out.write('$DISPLAY is set.\n')
else:
    out.write('$DISPLAY not set.\n')

out.write('`which aptitude`: %s\n' % os.popen('/usr/bin/which aptitude 2>&1').read().strip())

out.write('aptitude version information:\n')
# I would like to run `which aptitude`, but that raises security issues.
os.system('/usr/bin/aptitude --version 1>&3')

out.write('\n')

out.write('aptitude linkage:\n')
os.system('/usr/bin/ldd /usr/bin/aptitude 1>&3')
