# !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!! 
# This file is built by mktables from e.g. UnicodeData.txt.
# Any changes made here will be lost!

# This file is for internal use by the Perl program only.  The format and even
# name or existence of this file are subject to change without notice.  Don't
# use it directly.

#
# DecompositionType category 'Square'
#
return <<'END';
3250		
32CC	32CF	
3300	3357	
3371	33DF	
33FF		
END
