#!/bin/sh

# This is a hook script executed by the nvidia-installer
# (i.e. by running a NVIDIA-Linux-*.run file directly).

cat - << EOF | tee /dev/tty




If you want to use the nvidia-installer please uninstall the Debian packages
first.  The two methods of installation cannot be used at the same time.

EOF

for i in 10 9 8 7 6 5 4 3 2 1
do
	echo -ne "\rTerminating nvidia-installer in $i seconds.  " | tee /dev/tty
	sleep 1
done

echo "" | tee /dev/tty
echo "Killing nvidia-installer" | tee /dev/tty

# let's try to kill nvidia-installer
# yes, the missing 'r' is correct
pkill -x nvidia-installe

exit 1
