#!/bin/bash

. /etc/webc/functions.sh
. /etc/webc/webc.conf
while ! test -e /etc/webc/cmdline; do
	sleep 1
	test $SECONDS -gt 60 && exit 1
done

cmdline_has dns || exit 0

cat /etc/resolv.conf | sed '/nameserver/d' > /etc/resolv.conf.tmp

for i in $(cmdline_get dns)
do
	IFS=,; for dns in $i
	do
		echo nameserver $dns
	done
done >> /etc/resolv.conf.tmp

mv -f /etc/resolv.conf /etc/resolv.conf.old
mv -f /etc/resolv.conf.tmp /etc/resolv.conf
chmod 644 /etc/resolv.conf
