#!/bin/sh

set -e

# Stop the socket on remove and upgrade so acpid is not restarted via socket
# activation
if [ -d /run/systemd/system ] && [ "$1" = remove -o "$1" = upgrade ] ; then
        systemctl stop acpid.socket || true
fi

# Automatically added by dh_installinit/11.5.3
if [ -x "/etc/init.d/acpid" ] && [ "$1" = remove ]; then
	invoke-rc.d acpid stop || exit 1
fi
# End automatically added section

