#!/bin/sh

set -e

if [ "$1" = purge ]; then
	rm -f /var/backups/acpid-cruft.tar.gz

	# We restart hal on install and upgrades because acpid needs
	# /proc/acpi/event and hal might hold it (see postinst). On removal we
	# should restart hal to allow it to grab the file again.
	if [ -x /etc/init.d/hal ]; then
		invoke-rc.d hal restart
	fi
fi

# Automatically added by dh_installinit
if [ "$1" = "purge" ] ; then
	update-rc.d acpid remove >/dev/null
fi
# End automatically added section

