#!/bin/sh

set -e

if [ purge = "$1" ]; then
    rm -f /etc/default/console-setup
fi

if [ remove = "$1" -o purge = "$1" ]; then
    if [ ! -f /bin/setupcon ]; then
        rm -f /etc/console-setup/cached_*
    fi
fi


# Automatically added by dh_installdebconf
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section

