#!/bin/sh

set -e

if [ "$1" = purge ]
then
    rm -rf /etc/console
fi

# Automatically added by dh_installinit
if [ "$1" = "purge" ] ; then
	update-rc.d keymap.sh remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installdebconf
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section

