#!/bin/sh
set -e

# Conffiles that are now obsolete
dpkg-maintscript-helper rm_conffile /etc/cron.monthly/standard "3.0pl1-113" -- "$@"
dpkg-maintscript-helper rm_conffile /etc/cron.daily/standard "3.0pl1-124" -- "$@"

if [ "$1" = "purge" ]; then 
    rm -f /etc/cron.allow /etc/cron.deny
fi

# Automatically added by dh_installinit
if [ "$1" = "purge" ] ; then
	update-rc.d cron remove >/dev/null
fi
# End automatically added section

