#!/bin/sh

set -e

if [ -d /run/systemd/system ] && [ "$1" = remove ]; then
	# Before stopping dbus-daemon, ensure that it won't just be
	# reactivated by dbus.socket. The "invoke-rc.d dbus stop"
	# added by debhelper, below, will harmlessly not do anything.
	systemctl stop dbus.socket dbus.service || exit $?
fi

# Automatically added by dh_installinit
if [ -x "/etc/init.d/dbus" ] && [ "$1" = remove ]; then
	invoke-rc.d dbus stop || exit $?
fi
# End automatically added section


exit 0
