#!/bin/sh

set -e

# Convert installed-flavors to flavor/installed/*.
if test -e /var/lib/emacsen-common/installed-flavors
then
  for flavor in $(cat /var/lib/emacsen-common/installed-flavors)
  do
    touch "/var/lib/emacsen-common/state/flavor/installed/$flavor"
  done
  rm -f /var/lib/emacsen-common/installed-flavors
fi

/usr/lib/emacsen-common/emacs-package-install --postinst emacsen-common

# Automatically added by dh_installdeb/11.4
dpkg-maintscript-helper rm_conffile /etc/emacs/site-start.d/00debian-vars.el 3.0.3\~ emacsen-common -- "$@"
dpkg-maintscript-helper rm_conffile /etc/emacs/site-start.el 3.0.3\~ emacsen-common -- "$@"
# End automatically added section

