#! /bin/sh

set -e

CONF=/etc/fonts/local.conf

case "$1" in
	purge)
	    if [ -x /usr/bin/ucf ]; then
		ucf --purge $CONF
	    fi
	    rm -f $CONF
	    rm -rf /etc/fonts/conf.d
	    rmdir /usr/local/share/fonts 2>/dev/null || true
	    ;;
esac

# Automatically added by dh_installdebconf
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section

