#!/bin/sh

set -e

if [ ! -e /etc/initramfs-tools/modules ]; then
	sed '/^###/d' /usr/share/initramfs-tools/modules \
		> /etc/initramfs-tools/modules
fi

# Regenerate initramfs whenever we go to dpkg state `installed'
if [ "x$1" != xtriggered ]; then
	# this activates the trigger, if triggers are working
	update-initramfs -u
else
	# force it to actually happen
	DPKG_MAINTSCRIPT_PACKAGE='' update-initramfs -u
fi


