#!/bin/sh

set -e

dpkg-maintscript-helper rm_conffile /etc/init.d/keyboard-setup 1.138~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/init.d/console-setup 1.138~ -- "$@"
if [ purge = "$1" ]; then
    rm -f /etc/default/keyboard
fi

# Automatically added by dh_installdebconf
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section

