#!/bin/sh
set -e

case "$1" in
triggered)
	# This is triggered everytime an application installs a GIO
	# module into /usr/lib/gio/modules
	/usr/lib/glib-2.0/gio-querymodules /usr/lib/gio/modules
        exit 0
;;
esac

# Also handle the initial installation
if [ -d /usr/lib/gio/modules ]; then
    /usr/lib/glib-2.0/gio-querymodules /usr/lib/gio/modules
fi

# Automatically added by dh_makeshlibs
if [ "$1" = "configure" ]; then
	ldconfig
fi
# End automatically added section

