#!/bin/sh
set -e


if [ "$1" = "configure" ]
then

	if [ -x /usr/lib/nvidia/check-for-conflicting-opengl-libraries ]
	then
		/usr/lib/nvidia/check-for-conflicting-opengl-libraries
	fi

	if [ -x /usr/lib/nvidia/check-for-mismatching-nvidia-module ]
	then
		/usr/lib/nvidia/check-for-mismatching-nvidia-module 313.30
	fi

fi


# Automatically added by dh_makeshlibs
if [ "$1" = "configure" ]; then
	ldconfig
fi
# End automatically added section


exit 0
