#! /bin/sh
set -e

PACKAGE=libncursesw5

if dpkg --compare-versions "$2" lt-nl 5.9-7; then
    # Replace directory with symlink.
    if [ ! -L /usr/share/doc/$PACKAGE ] && \
	[ -d /usr/share/doc/$PACKAGE ]; then
        if rmdir /usr/share/doc/$PACKAGE 2>/dev/null; then
            ln -sf libtinfo5 /usr/share/doc/$PACKAGE
        fi
    fi
fi

# Automatically added by dh_makeshlibs
if [ "$1" = "configure" ]; then
	ldconfig
fi
# End automatically added section


exit 0
