#!/bin/sh
set -e

if [ "$1" = "configure" ]; then
	# <target: squeeze>
	# these files were left over by some old versions of the
	# nvidia-libvdpau* packages
	if [ -L /usr/lib/libvdpau_trace.so ]; then
		rm /usr/lib/libvdpau_trace.so || true
	fi
	if [ -L /usr/lib/libvdpau_nvidia.so ]; then
		rm /usr/lib/libvdpau_nvidia.so || true
	fi
	# </target: squeeze>
fi


# Automatically added by dh_makeshlibs
if [ "$1" = "configure" ]; then
	ldconfig
fi
# End automatically added section


exit 0
