#!/bin/sh -e

remove_etc_files() {
  rm -f /etc/modules
}

case "$1" in
    purge)
    remove_etc_files
    ;;

    remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;

    *)
    echo "$0 called with unknown argument '$1'" >&2
    exit 1
    ;;
esac

# Automatically added by dh_installinit
if [ "$1" = "purge" ] ; then
	update-rc.d module-init-tools remove >/dev/null
fi
# End automatically added section


exit 0
