#!/bin/sh

set -e

if dpkg-maintscript-helper supports rm_conffile; then
	dpkg-maintscript-helper rm_conffile \
		/etc/dhcp3/dhclient-enter-hooks.d/ntpdate 1:4.2.6+dfsg-1 -- "$@"
fi

if dpkg-maintscript-helper supports mv_conffile; then
	dpkg-maintscript-helper mv_conffile \
	/etc/dhcp3/dhclient-exit-hooks.d/ntpdate \
	/etc/dhcp/dhclient-exit-hooks.d/ntpdate \
	1:4.2.6.p1+dfsg-1 -- "$@"
fi



if [ "$1" = "purge" ]; then
	rm -rf /var/lib/ntpdate/
fi
