/.
/usr
/usr/bin
/usr/bin/dh_python2
/usr/share
/usr/share/apps
/usr/share/apps/konsole
/usr/share/apps/konsole/python.desktop
/usr/share/doc
/usr/share/doc/python2.7
/usr/share/doc/python
/usr/share/doc/python/faq
/usr/share/doc/python/faq/library.html
/usr/share/doc/python/faq/programming.html
/usr/share/doc/python/faq/installed.html
/usr/share/doc/python/faq/gui.html
/usr/share/doc/python/faq/windows.html
/usr/share/doc/python/faq/general.html
/usr/share/doc/python/faq/extending.html
/usr/share/doc/python/python-policy.sgml.gz
/usr/share/doc/python/python-policy.html
/usr/share/doc/python/python-policy.html/ch-module_packages.html
/usr/share/doc/python/python-policy.html/ch-programs.html
/usr/share/doc/python/python-policy.html/ap-packaging_tools.html
/usr/share/doc/python/python-policy.html/ch-embed.html
/usr/share/doc/python/python-policy.html/ch-other.html
/usr/share/doc/python/python-policy.html/ap-build_dependencies.html
/usr/share/doc/python/python-policy.html/ap-upgrade.html
/usr/share/doc/python/python-policy.html/index.html
/usr/share/doc/python/python-policy.html/ch-python.html
/usr/share/doc/python/copyright
/usr/share/doc/python/python-policy.txt.gz
/usr/share/doc/python/changelog.Debian.gz
/usr/share/doc/python/README.Debian
/usr/share/doc/python/FAQ.html
/usr/share/lintian
/usr/share/lintian/overrides
/usr/share/lintian/overrides/python
/usr/share/python
/usr/share/python/runtime.d
/usr/share/python/runtime.d/public_modules.rtremove
/usr/share/python/runtime.d/public_modules.rtinstall
/usr/share/python/dist_fallback
/usr/share/python/python.mk
/usr/share/perl5
/usr/share/perl5/Debian
/usr/share/perl5/Debian/Debhelper
/usr/share/perl5/Debian/Debhelper/Sequence
/usr/share/perl5/Debian/Debhelper/Sequence/python2.pm
/usr/share/debhelper
/usr/share/debhelper/autoscripts
/usr/share/debhelper/autoscripts/prerm-pyclean
/usr/share/debhelper/autoscripts/preinst-pycentral-clean
/usr/share/debhelper/autoscripts/postinst-pycompile
/usr/share/doc-base
/usr/share/doc-base/python-policy
/usr/share/man
/usr/share/man/man1
/usr/share/man/man1/dh_python2.1.gz
/usr/share/pixmaps
/usr/lib
/usr/lib/valgrind
/usr/lib/valgrind/python.supp
/usr/bin/pydoc
/usr/bin/pdb
/usr/bin/pygettext
/usr/bin/2to3
/usr/share/doc/python2.7/python-policy.sgml.gz
/usr/share/doc/python2.7/python-policy.html
/usr/share/doc/python2.7/python-policy.txt.gz
/usr/share/man/man1/pydoc.1.gz
/usr/share/man/man1/pdb.1.gz
/usr/share/man/man1/2to3.1.gz
/usr/share/man/man1/pygettext.1.gz
/usr/share/pixmaps/python.xpm
