#! /bin/sh

set -e

if [ "$1" = "remove" ]; then

    if [ -f /var/lib/python/python2.7_installed ]; then
	rm -f /var/lib/python/python2.7_installed
	rmdir --ignore-fail-on-non-empty /var/lib/python 2>/dev/null
    fi
fi

if [ "$1" = "purge" ]; then
    for d in `find /usr/lib/python2.7 -depth -type d -empty 2> /dev/null`; do \
        while rmdir $d 2> /dev/null; do d=`dirname $d`; done; \
    done
fi



exit 0
