#!/bin/sh -e

case "$1" in
  install|upgrade)
    if dpkg --compare-versions "$2" le "1.7.4p4-4"; then

      SUDOERS="/etc/sudoers"

      if [ -e "$SUDOERS" ]; then
        md5sum="$(md5sum $SUDOERS | sed -e 's/ .*//')"
        if [ "$md5sum" = "c5dab0f2771411ed7e67d6dab60a311f" ]; then
	    # move unchanged sudoers file to avoid conffile question
            mv "$SUDOERS" "$SUDOERS.pre-conffile"
        fi
      fi
    fi
  ;;
esac


