#!/bin/sh

set -e

# We are installing systemd-sysv but systemd is not running.
# This most likely means we are upgrading from another init, possibly a newer
# sysvinit version which created the initctl socket at /run/initctl.
# systemd's sysv tools expect the socket at /dev/initctl, so create the compat
# symlink ourselves.
if [ ! -e /sys/fs/cgroup/systemd ] ; then
    if [ ! -p /dev/initctl ] && [ -p /run/initctl ] ; then
        ln -sf /run/initctl /dev/initctl
    fi
fi


