#!/bin/sh
set -e

case "$1" in
    configure|abort-deconfigure|abort-remove)
	update-alternatives --install /usr/sbin/rmt rmt /usr/sbin/rmt-tar 50 \
		--slave /usr/share/man/man8/rmt.8.gz rmt.8.gz \
			/usr/share/man/man8/rmt-tar.8.gz 
    ;;
    upgrade)
    ;;
esac

# Automatically added by dh_installmime
if [ "$1" = "configure" ] && [ -x "`which update-mime 2>/dev/null`" ]; then
	update-mime
fi
# End automatically added section

