/.
/usr
/usr/share
/usr/share/lintian
/usr/share/lintian/overrides
/usr/share/lintian/overrides/x11-common
/usr/share/X11
/usr/share/doc
/usr/share/doc/x11-common
/usr/share/doc/x11-common/changelog.Debian.old.gz
/usr/share/doc/x11-common/copyright
/usr/share/doc/x11-common/NEWS.Debian.gz
/usr/share/doc/x11-common/TODO
/usr/share/doc/x11-common/changelog.gz
/usr/share/man
/usr/share/man/man5
/usr/share/man/man5/Xwrapper.config.5.gz
/usr/share/man/man5/Xsession.options.5.gz
/usr/share/man/man5/Xsession.5.gz
/usr/include
/usr/include/X11
/usr/lib
/usr/lib/X11
/usr/bin
/etc
/etc/X11
/etc/X11/Xreset
/etc/X11/Xresources
/etc/X11/Xresources/x11-common
/etc/X11/rgb.txt
/etc/X11/Xreset.d
/etc/X11/Xreset.d/README
/etc/X11/Xsession.options
/etc/X11/Xsession
/etc/X11/Xsession.d
/etc/X11/Xsession.d/35x11-common_xhost-local
/etc/X11/Xsession.d/30x11-common_xresources
/etc/X11/Xsession.d/40x11-common_xsessionrc
/etc/X11/Xsession.d/20x11-common_process-args
/etc/X11/Xsession.d/99x11-common_start
/etc/X11/Xsession.d/50x11-common_determine-startup
/etc/X11/Xsession.d/90x11-common_ssh-agent
/etc/init.d
/etc/init.d/x11-common
/usr/share/X11/rgb.txt
/usr/bin/X11
