/.
/var
/var/lib
/var/lib/xkb
/var/lib/xkb/README.compiled
/usr
/usr/share
/usr/share/doc
/usr/share/doc/xserver-common
/usr/share/doc/xserver-common/copyright
/usr/share/doc/xserver-common/changelog.Debian.gz
/usr/share/doc/xserver-common/changelog.gz
/usr/share/man
/usr/share/man/man1
/usr/share/man/man1/Xserver.1.gz
/usr/lib
/usr/lib/xorg
/usr/lib/xorg/protocol.txt
