#!/bin/sh
# /etc/cron.daily/calendar: BSD mainutils calendar daily maintenance script
# Written by Austin Donnelly <and1000@debian.org>

# Comment the following line if you'd like all of your users'
# ~/calendar files to be checked daily.  Calendar will send them mail
# to remind them of upcoming events.  See calendar(1) for more details.
exit 0

[ -x /usr/sbin/sendmail ] || exit 0
if [ ! -x /usr/bin/cpp ]; then
  echo "The cpp package is needed to run calendar."
  exit 1
fi

/usr/bin/calendar -a
