#!/bin/sh

## live-config(7) - System Configuration Scripts
## Copyright (C) 2006-2012 Daniel Baumann <daniel@debian.org>
##
## This program comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
## This is free software, and you are welcome to redistribute it
## under certain conditions; see COPYING for details.


Debconf ()
{
	# Checking if package is installed or already configured
	if [ ! -e /var/lib/dpkg/info/debconf.list ] || \
	   [ -e /var/lib/live/config/debconf ]
	then
		return
	fi

	echo -n " debconf"

	# Reading kernel command line
	for _PARAMETER in ${_CMDLINE}
	do
		case "${_PARAMETER}" in
			live-config.debconf-preseed=*|debconf-preseed=*)
				LIVE_DEBCONF_PRESEED="${_PARAMETER#*debconf-preseed=}"
				;;
		esac
	done

	Configure_debconf
}

Configure_debconf ()
{
	if [ -z "${LIVE_DEBCONF_PRESEED}" ]
	then
		return
	fi

	for _PRESEED in $(echo ${LIVE_PRESEEDS} | sed -e 's/|/ /g')
	do
		case "${_PRESEED}" in
			filesystem)
				if ls /lib/live/config-preseed/* 2>&1
				then
					_PRESEEDS="${_PRESEEDS} $(for _FILE in /lib/live/config-preseed/*; do echo file://${_FILE}; done)"
				fi
				;;

			medium)
				if ls /lib/live/mount/medium/live/config-preseed/* 2>&1
				then
					_PRESEEDS="${_PRESEEDS} $(for _FILE in /lib/live/mount/medium/live/config-preseed/*; do echo file://${_FILE}; done)"
				fi
				;;

			*)
				_PRESEEDS="${_PRESEEDS} ${_PRESEED}"
				;;
		esac
	done

	for _PRESEED in ${_PRESEEDS}
	do
		_TMPFILE="$(mktemp -t live-config.XXXXXXXX)"

		if echo "${_PRESEED}" | grep -qs file://
		then
			# local file
			cp $(echo ${_PRESEED} | sed 's|file://||') "${_TMPFILE}"
		else
			# remote file
			Setup_network

			wget --quiet "${_PRESEED}" -O "${_TMPFILE}"
		fi

		debconf-set-selections < "${_TMPFILE}"
		rm -f "${_TMPFILE}"
	done

	# Creating state file
	touch /var/lib/live/config/debconf
}

Debconf
