#!/bin/sh

## live-config(7) - System Configuration Components
## Copyright (C) 2006-2014 Daniel Baumann <mail@daniel-baumann.ch>
##
## This program comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
## This is free software, and you are welcome to redistribute it
## under certain conditions; see COPYING for details.


#set -e

Cmdline ()
{
	# Reading kernel command line
	for _PARAMETER in ${LIVE_CONFIG_CMDLINE}
	do
		case "${_PARAMETER}" in
			live-config.username=*|username=*)
				LIVE_USERNAME="${_PARAMETER#*username=}"
				;;
		esac
	done
}

Init ()
{
	# Checking if package is installed or already configured
	if [ ! -e /var/lib/dpkg/info/gdm3.list ] || \
	   [ -e /var/lib/live/config/gdm3 ]
	then
		exit 0
	fi

	echo -n " gdm3"
}

Config ()
{
	# Checking if package is already configured
	if grep -qs AutomaticLoginEnable=true /etc/gdm3/daemon.conf
	then
		exit 0
	fi

	_GDM3_OPTIONS="AutomaticLoginEnable=true\n\
AutomaticLogin=${LIVE_USERNAME}\n\
TimedLoginEnable=true\n\
TimedLogin=${LIVE_USERNAME}\n\
TimedLoginDelay=5"

	sed -i -e "s|\[daemon\]|\[daemon\]\n${_GDM3_OPTIONS}|" /etc/gdm3/daemon.conf

	# Avoid xinit
	touch /var/lib/live/config/xinit

	# Creating state file
	touch /var/lib/live/config/gdm3
}

Cmdline
Init
Config
