#!/bin/sh

## live-config(7) - System Configuration Scripts
## Copyright (C) 2006-2011 Daniel Baumann <daniel@debian.org>
##
## live-config comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
## This is free software, and you are welcome to redistribute it
## under certain conditions; see COPYING for details.


Lxdm ()
{
	# Checking if package is installed or already configured
	if [ ! -e /var/lib/dpkg/info/lxdm.list ]
	then
		return
	fi

	if [ -e /var/lib/live/config/lxdm ]
	then
		# Avoid xinit
		_X11="true"
		export _X11

		return
	fi

	echo -n " lxdm"

	Configure_lxdm
}

Configure_lxdm ()
{
	if [ -e /etc/lxdm/lxdm.conf ]
	then
		sed -i -r -e "s|^#?autologin=.*\$|autologin=${LIVE_USERNAME}|" \
			  -e "s|^#?session.*\$|session|" \
		/etc/lxdm/lxdm.conf
	fi

	# Avoid xinit
	_X11="true"
	export _X11

	# Creating state file
	touch /var/lib/live/config/lxdm
}

Lxdm
