#!/bin/sh

## live-config(7) - System Configuration Components
## Copyright (C) 2006-2014 Daniel Baumann <mail@daniel-baumann.ch>
##
## This program comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
## This is free software, and you are welcome to redistribute it
## under certain conditions; see COPYING for details.


#set -e

Cmdline ()
{
	# Reading kernel command line
	for _PARAMETER in ${LIVE_CONFIG_CMDLINE}
	do
		case "${_PARAMETER}" in
			live-config.username=*|username=*)
				LIVE_USERNAME="${_PARAMETER#*username=}"
				;;
		esac
	done
}

Init ()
{
	# Checking if package is installed or already configured
	if [ ! -e /var/lib/dpkg/info/kdm.list ] || \
	   [ -e /var/lib/live/config/kdm ]
	then
		exit 0
	fi

	echo -n " kdm"
}

Config ()
{
	if [ ! -e /etc/kde4/kdm/kdmrc ]
	then
		exit 0
	fi

	if [ "${LIVE_CONFIG_NOAUTOLOGIN}" != "true" ] && [ "${LIVE_CONFIG_NOX11AUTOLOGIN}" != "true" ]
	then
		# autologin
		sed -i -r -e "s|^#.*AutoLoginEnable=.*\$|AutoLoginEnable=true|" \
			  -e "s|^#.*AutoLoginAgain=.*\$|AutoLoginAgain=true|" \
			  -e "s|^#.*AutoLoginUser=.*\$|AutoLoginUser=${LIVE_USERNAME}|" \
		/etc/kde4/kdm/kdmrc
	fi

	# language
	if [ -n "${_LANGUAGE}" ]
	then
		sed -i -r -e "s|^#.*Language=.*\$|Language=${_LANGUAGE}|" \
			/etc/kde4/kdm/kdmrc
	fi

	# Avoid xinit
	touch /var/lib/live/config/xinit

	# Creating state file
	touch /var/lib/live/config/kdm
}

Cmdline
Init
Config
