#!/bin/sh

## live-config(7) - System Configuration Scripts
## Copyright (C) 2006-2011 Daniel Baumann <daniel@debian.org>
##
## live-config comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
## This is free software, and you are welcome to redistribute it
## under certain conditions; see COPYING for details.


Nodm ()
{
	# Checking if package is installed or already configured
	if [ ! -e /var/lib/dpkg/info/nodm.list ]
	then
		return
	fi

	if [ -e /var/lib/live/config/nodm ]
	then
		# Avoid xinit
		_X11="true"
		export _X11

		return
	fi

	echo -n " nodm"

	Configure_nodm
}

Configure_nodm ()
{
	# autologin
	sed -i -r -e "s|^NODM_ENABLED=.*\$|NODM_ENABLED=true|" \
		  -e "s|^NODM_USER=.*\$|NODM_USER=${LIVE_USERNAME}|" \
	/etc/default/nodm

cat > /tmp/debconf.live << EOF
nodm nodm/enabled boolean true
nodm nodm/user string ${LIVE_USERNAME}
EOF

	debconf-set-selections < /tmp/debconf.live
	rm -f /tmp/debconf.live

	# Avoid xinit
	_X11="true"
	export _X11

	# Creating state file
	touch /var/lib/live/config/nodm
}

Nodm
