#!/bin/sh

## live-config(7) - System Configuration Scripts
## Copyright (C) 2006-2012 Daniel Baumann <daniel@debian.org>
##
## This program comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
## This is free software, and you are welcome to redistribute it
## under certain conditions; see COPYING for details.


Kdm ()
{
	# Checking if package is installed or already configured
	if [ ! -e /var/lib/dpkg/info/kdm.list ]
	then
		return
	fi

	if [ -e /var/lib/live/config/kdm ]
	then
		# Avoid xinit
		_X11="true"
		export _X11

		return
	fi

	echo -n " kdm"

	# Reading kernel command line
	for _PARAMETER in ${_CMDLINE}
	do
		case "${_PARAMETER}" in
			live-config.username=*|username=*)
				LIVE_USERNAME="${_PARAMETER#*username=}"
				;;
		esac
	done

	Configure_kdm
}

Configure_kdm ()
{
	if [ ! -e /etc/kde4/kdm/kdmrc ]
	then
		return
	fi

	# autologin
	sed -i -r -e "s|^#.*AutoLoginEnable=.*\$|AutoLoginEnable=true|" \
		  -e "s|^#.*AutoLoginAgain=.*\$|AutoLoginAgain=true|" \
		  -e "s|^#.*AutoLoginUser=.*\$|AutoLoginUser=${LIVE_USERNAME}|" \
	/etc/kde4/kdm/kdmrc

	# language
	if [ -n "${_LANGUAGE}" ]
	then
		sed -i -r -e "s|^#.*Language=.*\$|Language=${_LANGUAGE}|" \
			/etc/kde4/kdm/kdmrc
	fi

	# Avoid xinit
	_X11="true"
	export _X11

	# Creating state file
	touch /var/lib/live/config/kdm
}

Kdm
