#!/bin/sh

## live-config(7) - System Configuration Scripts
## Copyright (C) 2006-2011 Daniel Baumann <daniel@debian.org>
##
## live-config comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
## This is free software, and you are welcome to redistribute it
## under certain conditions; see COPYING for details.


Slim ()
{
	# Checking if package is installed or already configured
	if [ ! -e /var/lib/dpkg/info/slim.list ]
	then
		return
	fi

	if [ -e /var/lib/live/config/slim ]
	then
		# Avoid xinit
		_X11="true"
		export _X11

		return
	fi

	echo -n " slim"

	Configure_slim
}

Configure_slim ()
{
	# Checking if if package is already configured differently
	if grep -qs "^auto_login" /etc/slim.conf
	then
		return
	fi

	# autologin
	sed -i -r -e "s|^#?auto_login.*\$|auto_login yes|" \
		  -e "s|^#?default_user.*\$|default_user ${LIVE_USERNAME}|" \
	/etc/slim.conf

	# Avoid xinit
	_X11="true"
	export _X11

	# Creating state file
	touch /var/lib/live/config/slim
}

Slim
