#!/bin/sh

## live-config(7) - System Configuration Scripts
## Copyright (C) 2006-2012 Daniel Baumann <daniel@debian.org>
##
## This program comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
## This is free software, and you are welcome to redistribute it
## under certain conditions; see COPYING for details.


Lightdm ()
{
	# Checking if package is installed or already configured
	if [ ! -e /var/lib/dpkg/info/lightdm.list ]
	then
		return
	fi

	if [ -e /var/lib/live/config/lightdm ]
	then
		# Avoid xinit
		_X11="true"
		export _X11

		return
	fi

	echo -n " lightdm"

	# Reading kernel command line
	for _PARAMETER in ${_CMDLINE}
	do
		case "${_PARAMETER}" in
			live-config.username=*|username=*)
				LIVE_USERNAME="${_PARAMETER#*username=}"
				;;
		esac
	done

	Configure_lightdm
}

Configure_lightdm ()
{
	if [ -e /etc/lightdm/lightdm.conf ]
	then
		sed -i -r -e "s|^#.*autologin-user=.*\$|autologin-user=${LIVE_USERNAME}|" \
			  -e "s|^#.*autologin-user-timeout=.*\$|autologin-user-timeout=5|" \
		/etc/lightdm/lightdm.conf
	fi

	# Avoid xinit
	_X11="true"
	export _X11

	# Creating state file
	touch /var/lib/live/config/lightdm
}

Lightdm
