#!/bin/sh

## live-config(7) - System Configuration Components
## Copyright (C) 2006-2014 Daniel Baumann <mail@daniel-baumann.ch>
##
## This program comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
## This is free software, and you are welcome to redistribute it
## under certain conditions; see COPYING for details.


#set -e

Cmdline ()
{
	# Reading kernel command line
	for _PARAMETER in ${LIVE_CONFIG_CMDLINE}
	do
		case "${_PARAMETER}" in
			live-config.username=*|username=*)
				LIVE_USERNAME="${_PARAMETER#*username=}"
				;;
		esac
	done
}

Init ()
{
	# Checking if package is installed or already configured
	if [ ! -e /var/lib/dpkg/info/lxdm.list ] || \
	   [ -e /var/lib/live/config/lxdm ]
	then
		exit 0
	fi

	echo -n " lxdm"
}

Config ()
{
	# Debian
	if [ -e /etc/lxdm/lxdm.conf ]
	then
		sed -i -r -e "s|^#.*autologin=.*\$|autologin=${LIVE_USERNAME}|" \
			  -e "s|^#.*session.*\$|session|" \
		/etc/lxdm/lxdm.conf
	fi

	# Ubuntu
	if [ -e /etc/lxdm/default.conf ]
	then
		sed -i -r -e "s|^#.*autologin=.*\$|autologin=${LIVE_USERNAME}|" \
			  -e "s|^#.*session.*\$|session=/usr/bin/startlubuntu|" \
		/etc/lxdm/default.conf
	fi

	# Avoid xinit
	touch /var/lib/live/config/xinit

	# Creating state file
	touch /var/lib/live/config/lxdm
}

Cmdline
Init
Config
