#!/bin/sh

## live-config(7) - System Configuration Scripts
## Copyright (C) 2006-2011 Daniel Baumann <daniel@debian.org>
##
## live-config comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
## This is free software, and you are welcome to redistribute it
## under certain conditions; see COPYING for details.


Console_common ()
{
	# Checking if package is installed or already configured
	if [ ! -e /var/lib/dpkg/info/console-common.list ] || \
	   [ -e /var/lib/live/config/console-common ]
	then
		return
	fi

	echo -n " console-common"

	Configure_console_common
}

Configure_console_common ()
{
	if [ -n "${_KEYBOARD}" ]
	then
		install-keymap ${_KEYBOARD}

		# Creating state file
		touch /var/lib/live/config/console-common
	fi
}

Console_common
