#!/bin/sh

## live-config(7) - System Configuration Scripts
## Copyright (C) 2006-2011 Daniel Baumann <daniel@debian.org>
##
## live-config comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
## This is free software, and you are welcome to redistribute it
## under certain conditions; see COPYING for details.


Console_setup ()
{
	# Checking if package is installed or already configured
	if [ ! -e /var/lib/dpkg/info/console-setup.list ] || \
	   [ -e /var/lib/live/config/console-setup ]
	then
		return
	fi

	# Don't run on squeeze and newer
	if [ -e /var/lib/dpkg/info/keyboard-configuration.list ]
	then
		return
	fi

	echo -n " console-setup"

	Configure_console_setup
}

Configure_console_setup ()
{
	if [ -n "${LIVE_KEYBOARD_MODEL}" ]
	then
		echo "console-setup console-setup/modelcode select ${LIVE_KEYBOARD_MODEL}" >> /tmp/debconf.live

		sed -i -e "s|^XKBMODEL=.*$|XKBMODEL=\"${LIVE_KEYBOARD_MODEL}\"|" /etc/default/console-setup
	fi

	if [ -n "${LIVE_KEYBOARD_LAYOUTS}" ]
	then
		echo "console-setup console-setup/layoutcode select ${LIVE_KEYBOARD_LAYOUTS}" >> /tmp/debconf.live

		sed -i -e "s|^XKBLAYOUT=.*$|XKBLAYOUT=\"${LIVE_KEYBOARD_LAYOUTS}\"|" /etc/default/console-setup
	fi

	if [ -n "${LIVE_KEYBOARD_VARIANT}" ]
	then
		echo "console-setup console-setup/variantcode select ${LIVE_KEYBOARD_VARIANT}" >> /tmp/debconf.live

		sed -i -e "s|^XKBVARIANT=.*$|XKBVARIANT=\"${LIVE_KEYBOARD_VARIANT}\"|" /etc/default/console-setup
	fi

	if [ -n "${LIVE_KEYBOARD_OPTIONS}" ]
	then
		echo "console-setup console-setup/variantcode string ${LIVE_KEYBOARD_OPTIONS}" >> /tmp/debconf.live

		sed -i -e "s|^XKBOPTIONS=.*$|XKBOPTIONS=\"${LIVE_KEYBOARD_OPTIONS}\"|" /etc/default/console-setup
	fi

	if [ -e /tmp/debconf.live ]
	then
		debconf-set-selections < /tmp/debconf.live
		rm -f /tmp/debconf.live

		# Creating state file
		touch /var/lib/live/config/console-setup
	fi
}

Console_setup
