#!/bin/sh

## live-config(7) - System Configuration Scripts
## Copyright (C) 2006-2011 Daniel Baumann <daniel@debian.org>
##
## live-config comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
## This is free software, and you are welcome to redistribute it
## under certain conditions; see COPYING for details.


Sysv_rc ()
{
	# Checking if package is installed or already configured
	if [ ! -e /var/lib/dpkg/info/sysv-rc.list ] || \
	   [ -e /var/lib/live/config/sysv-rc ]
	then
		return
	fi

	echo -n " sysv-rc"

	Configure_sysv_rc
}

Configure_sysv_rc ()
{
	if [ -n "${LIVE_SYSV_RC}" ]
	then
		for SERVICE in $(echo ${LIVE_SYSV_RC} | sed -e 's|,| |g')
		do
			update-rc.d -f ${SERVICE} remove | \
			grep -v "update-rc.d: using dependency based boot sequencing"
		done
	fi

	# Creating state file
	touch /var/lib/live/config/sysv-rc
}

Sysv_rc
