#!/bin/sh

## live-config(7) - System Configuration Scripts
## Copyright (C) 2006-2012 Daniel Baumann <daniel@debian.org>
##
## This program comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
## This is free software, and you are welcome to redistribute it
## under certain conditions; see COPYING for details.


Sysv_rc ()
{
	# Checking if package is installed or already configured
	if [ ! -e /var/lib/dpkg/info/sysv-rc.list ] || \
	   [ -e /var/lib/live/config/sysv-rc ]
	then
		return
	fi

	echo -n " sysv-rc"

	# Reading kernel command line
	for _PARAMETER in ${_CMDLINE}
	do
		case "${_PARAMETER}" in
			live-config.sysv-rc=*|sysv-rc=*)
				LIVE_SYSV_RC="${_PARAMETER#*sysv-rc=}"
				;;
		esac
	done

	Configure_sysv_rc
}

Configure_sysv_rc ()
{
	if [ -n "${LIVE_SYSV_RC}" ]
	then
		for _SERVICE in $(echo ${LIVE_SYSV_RC} | sed -e 's|,| |g')
		do
			update-rc.d -f ${_SERVICE} remove | \
			grep -v "update-rc.d: using dependency based boot sequencing" || true
		done
	fi

	# Creating state file
	touch /var/lib/live/config/sysv-rc
}

Sysv_rc
