#!/bin/sh

## live-config(7) - System Configuration Scripts
## Copyright (C) 2006-2012 Daniel Baumann <daniel@debian.org>
##
## This program comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
## This is free software, and you are welcome to redistribute it
## under certain conditions; see COPYING for details.


Kaboom ()
{
	# Checking if package is installed or already configured
	if [ ! -e /var/lib/dpkg/info/kaboom.list ] || \
	   [ -e /var/lib/live/config/kaboom ]
	then
		return
	fi

	echo -n " kaboom"

	# Reading kernel command line
	for _PARAMETER in ${_CMDLINE}
	do
		case "${_PARAMETER}" in
			live-config.username=*|username=*)
				LIVE_USERNAME="${_PARAMETER#*username=}"
				;;
		esac
	done

	Configure_kaboom
}

Configure_kaboom ()
{
	sudo -u "${LIVE_USERNAME}" sh -c "mkdir -p /home/${LIVE_USERNAME}/.local && touch /home/${LIVE_USERNAME}/.local/kaboom"

	# Creating state file
	touch /var/lib/live/config/kaboom
}

Kaboom
