#!/bin/sh

## live-config(7) - System Configuration Scripts
## Copyright (C) 2006-2011 Daniel Baumann <daniel@debian.org>
##
## live-config comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
## This is free software, and you are welcome to redistribute it
## under certain conditions; see COPYING for details.


Kde_services ()
{
	# Checking if package is installed or already configured
	# we're only checking for KDE4 here (FIXME).
	if [ ! -e /usr/share/kde4 ] || \
	   [ -e /var/lib/live/config/kde-services ]
	then
		return
	fi

	echo -n " kde-services"

	Configure_kde_services
}

Configure_kde_services ()
{
	# Enabling keyboard selector
	if echo "${LIVE_KEYBOARD_LAYOUTS}" | grep -qs ','
	then
		if [ ! -e "/home/${LIVE_USERNAME}/.kde/share/config/kxkbrc" ]
		then
			mkdir -p "/home/${LIVE_USERNAME}/.kde/share/config/"

cat > "/home/${LIVE_USERNAME}/.kde/share/config/kxkbrc" << EOF
[Layout]
DisplayNames=${LIVE_KEYBOARD_LAYOUTS}
IndicatorOnly=false
LayoutList=${LIVE_KEYBOARD_LAYOUTS}
ShowFlag=true
SwitchMode=Global
Use=true
EOF

			chown ${LIVE_USERNAME}:${LIVE_USERNAME} "/home/${LIVE_USERNAME}/.kde" -R
		fi
	fi

	# Disabling unnecessary KDE services
	rm -f /usr/share/autostart/kab2kabc.desktop
	rm -f /usr/share/autostart/kaddressbookmigrator.desktop
	rm -f /usr/share/autostart/korgac.desktop
	rm -f /usr/share/autostart/printer-applet.desktop
	rm -f /usr/share/autostart/nepomukserver.desktop
	rm -f /usr/share/kde4/services/kwalletd.desktop
	rm -f /usr/share/kde4/services/kded/kpackagekitd.desktop
	rm -f /usr/share/kde4/services/kded/freespacenotifier.desktop
	rm -f /usr/share/kde4/services/plasma-runner-contacts.desktop  # starts akonadi
	rm -f /usr/share/kde4/services/kded/notificationhelper.desktop
	rm -f /usr/share/kde4/services/plasma-dataengine-calendar.desktop # starts akonadi

	# should enable kxkb in ~/.kde/share/config/kxkbrc
	# if multiple layouts are specified. gnome does it per default.

	# Creating state file
	touch /var/lib/live/config/kde-services
}

Kde_services
