#!/bin/sh

## live-config(7) - System Configuration Scripts
## Copyright (C) 2006-2011 Daniel Baumann <daniel@debian.org>
##
## live-config comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
## This is free software, and you are welcome to redistribute it
## under certain conditions; see COPYING for details.


Kpersonalizer ()
{
	# Checking if package is installed or already configured
	if [ ! -e /var/lib/dpkg/info/kpersonalizer.list ] || \
	   [ -e /var/lib/live/config/kpersonalizer ]
	then
		return
	fi

	echo -n " kpersonalizer"

	Configure_kpersonalizer
}

Configure_kpersonalizer ()
{
	# Checking if apckage is already configured differently
	if grep -qs FirstLogin /etc/kde3/kpersonalizerrc
	then
		return
	fi

cat > /etc/kde3/kpersonalizerrc << EOF
[General]
FirstLogin=false
EOF

	# Creating state file
	touch /var/lib/live/config/kpersonalizer
}

Kpersonalizer
