#!/bin/sh

## live-config(7) - System Configuration Scripts
## Copyright (C) 2006-2011 Daniel Baumann <daniel@debian.org>
##
## live-config comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
## This is free software, and you are welcome to redistribute it
## under certain conditions; see COPYING for details.


Debian_installer_launcher ()
{
	# Checking if package is installed or already configured
	if [ ! -e /var/lib/dpkg/info/debian-installer-launcher.list ] || \
	   [ -e /var/lib/live/config/debian-installer-launcher ]
	then
		return
	fi

	echo -n " debian-installer-launcher"

	Configure_debian_installer_launcher
}

Configure_debian_installer_launcher ()
{
	# KDE4 needs the desktop file somewhere else,
	# otherwise no Home and Trash icons on the desktop.
	if [ -d  /usr/share/kde4/apps/kio_desktop/DesktopLinks ] && \
	   [ -e /var/lib/dpkg/info/xdg-user-dirs.list ]
	then
		install -D -o ${LIVE_USERNAME} -g ${LIVE_USERNAME} /usr/share/applications/debian-installer-launcher.desktop /usr/share/kde4/apps/kio_desktop/DesktopLinks/debian-installer-launcher.desktop
	else
		install -D -o ${LIVE_USERNAME} -g ${LIVE_USERNAME} /usr/share/applications/debian-installer-launcher.desktop /home/${LIVE_USERNAME}/Desktop/debian-installer-launcher.desktop
		chown ${LIVE_USERNAME}:${LIVE_USERNAME} /home/${LIVE_USERNAME}/Desktop -R
	fi

	# Creating state file
	touch /var/lib/live/config/debian-installer-launcher
}

Debian_installer_launcher
