#!/bin/sh

## live-config(7) - System Configuration Scripts
## Copyright (C) 2006-2011 Daniel Baumann <daniel@debian.org>
##
## live-config comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
## This is free software, and you are welcome to redistribute it
## under certain conditions; see COPYING for details.


Module_init_tools ()
{
	# Checking if package is installed
	case "$(dpkg --print-architecture)" in
		powerpc|ppc64)
			# Checking if package is already configured
			if [ -e /var/lib/live/config/module-init-tools ]
			then
				return
			fi
			;;

		*)
			return
			;;
	esac

	echo -n " module-init-tools"

	Configure_module_init_tools
}

Configure_module_init_tools ()
{
	# Checking if apckage is already configured differently
	if grep -qs "snd_powermac" /etc/modules
	then
		return
	fi

	# Preconfiguring /etc/modules
	echo "snd_powermac" >> /etc/modules

	# Creating state file
	touch /var/lib/live/config/module-init-tools
}

Module_init_tools
