#!/bin/sh

## live-config(7) - System Configuration Components
## Copyright (C) 2006-2015 Daniel Baumann <mail@daniel-baumann.ch>
##
## This program comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
## This is free software, and you are welcome to redistribute it
## under certain conditions; see COPYING for details.


#set -e

Init ()
{
	# Checking if package is installed
	if [ ! -e /var/lib/dpkg/info/anacron.list ] || \
	   [ -e /var/lib/live/config/anacron ]
	then
		exit 0
	fi

	echo -n " anacron"
}

Config ()
{
	# This has the nice side effect of the cron.{daily,weekly,monthly} jobs
	# in /etc/crontab remaining disabled, yet also not run by anacron

	# Diverting /usr/sbin/anacron
	if [ ! -e /usr/sbin/anacron.orig.anacron ]
	then
		dpkg-divert --quiet --package live-config --add --rename --divert /usr/sbin/anacron.orig.anacron /usr/sbin/anacron

		ln -s /bin/true /usr/sbin/anacron
	fi

	# Creating state file
	touch /var/lib/live/config/anacron
}

Init
Config
