#!/bin/sh

## live-config(7) - System Configuration Scripts
## Copyright (C) 2006-2011 Daniel Baumann <daniel@debian.org>
##
## live-config comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
## This is free software, and you are welcome to redistribute it
## under certain conditions; see COPYING for details.


Sslcert ()
{
	# Checking if package is installed
	if [ ! -e /var/lib/dpkg/info/sslcert.list ] || \
	   [ -e /var/lib/live/config/sslcert ]
	then
		return
	fi

	echo -n " sslcert"

	Configure_sslcert
}

Configure_sslcert ()
{
	make-ssl-cert generate-default-snakeoil --force-overwrite

	# Creating state file
	touch /var/lib/live/config/sslcert
}

Sslcert
