#!/bin/sh

## live-config(7) - System Configuration Scripts
## Copyright (C) 2006-2011 Daniel Baumann <daniel@debian.org>
##
## live-config comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
## This is free software, and you are welcome to redistribute it
## under certain conditions; see COPYING for details.


Anacron ()
{
	# Checking if package is installed
	if [ ! -e /var/lib/dpkg/info/anacron.list ] || \
	   [ -e /var/lib/live/config/anacron ]
	then
		return
	fi

	echo -n " anacron"

	Configure_anacron
}

Configure_anacron ()
{
	# This has the nice side effect of the cron.{daily,weekly,monthly} jobs
	# in /etc/crontab remaining disabled, yet also not run by anacron
	dpkg-divert --quiet --package live-config --add --rename --divert /usr/sbin/anacron.debian /usr/sbin/anacron

	ln -s /bin/true /usr/sbin/anacron

	# Creating state file
	touch /var/lib/live/config/anacron
}

Anacron
