#!/bin/sh

## live-config(7) - System Configuration Scripts
## Copyright (C) 2006-2011 Daniel Baumann <daniel@debian.org>
##
## live-config comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
## This is free software, and you are welcome to redistribute it
## under certain conditions; see COPYING for details.


Util_linux ()
{
	# Checking if package is installed
	if [ ! -e /var/lib/dpkg/info/util-linux.list ] || \
	   [ -e /var/lib/live/config/util-linux ]
	then
		return
	fi

	echo -n " util-linux"

	Configure_util_linux
}

Configure_util_linux ()
{
	rm -f /etc/rc?.d/*hwclock*

	# Creating state file
	touch /var/lib/live/config/util-linux
}

Util_linux
