#!/bin/sh

## live-config(7) - System Configuration Scripts
## Copyright (C) 2006-2011 Daniel Baumann <daniel@debian.org>
##
## live-config comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
## This is free software, and you are welcome to redistribute it
## under certain conditions; see COPYING for details.


Login ()
{
	# Checking if package is installed
	if [ ! -e /var/lib/dpkg/info/login.list ] || \
	   [ -e /var/lib/live/config/login ]
	then
		return
	fi

	echo -n " login"

	Configure_login
}

Configure_login ()
{
	# lastlog with autologin doesn't make sense
	sed -i '/^[^#].*pam_lastlog\.so/s/^/# /' /etc/pam.d/login

	# Creating state file
	touch /var/lib/live/config/login
}

Login
