#!/bin/sh

## live-config(7) - System Configuration Components
## Copyright (C) 2006-2015 Daniel Baumann <mail@daniel-baumann.ch>
##
## This program comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
## This is free software, and you are welcome to redistribute it
## under certain conditions; see COPYING for details.


#set -e

Cmdline ()
{
	# Reading kernel command line
	for _PARAMETER in ${LIVE_CONFIG_CMDLINE}
	do
		case "${_PARAMETER}" in
			live-config.username=*|username=*)
				LIVE_USERNAME="${_PARAMETER#*username=}"
				;;
		esac
	done
}

Init ()
{
	# Checking if package is installed or already configured
	if [ ! -e /var/lib/dpkg/info/xscreensaver.list ] || \
	   [ -e /var/lib/live/config/xscreensaver ]
	then
		exit 0
	fi

	echo -n " xscreensaver"
}

Config ()
{
	if ! grep -qs '^lock:' "/home/${LIVE_USERNAME}/.xscreensaver"
	then
		echo "lock: False" >> "/home/${LIVE_USERNAME}/.xscreensaver"
	fi

	# Creating state file
	touch /var/lib/live/config/xscreensaver
}

Cmdline
Init
Config
