#!/bin/sh

## live-config(7) - System Configuration Components
## Copyright (C) 2019 Raphael Hertzog <raphael@offensive-security.com>
##
## This program comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
## This is free software, and you are welcome to redistribute it
## under certain conditions; see COPYING for details.

# XXX: Can be dropped when https://github.com/systemd/systemd/issues/12492
# is fixed

if [ -e /etc/nsswitch.conf.nss-systemd ]; then
    # Restore original nsswitch.conf file
    mv /etc/nsswitch.conf.nss-systemd /etc/nsswitch.conf
fi
