#!/bin/sh
# reportbug output generator script for cron package

# reportbug expects output on fd 3
exec 1>&3 2>&3

echo "--- EDITOR:"
[ -n "$EDITOR" ] || echo "not set"
echo

echo "--- usr/bin/editor:"
readlink -f /usr/bin/editor
echo

echo "--- /usr/bin/crontab:"
ls -l /usr/bin/crontab
echo

echo "--- /var/spool/cron"
ls -ld /var/spool/cron
echo

echo "--- /var/spool/cron/crontabs"
ls -ld /var/spool/cron/crontabs
echo
