#!/bin/sh
### BEGIN INIT INFO
# Provides:          bumblebeed
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Should-Start:      kdm gdm nvidia-kernel
# Should-Stop:       kdm gdm
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Bumblebee supporting nVidia Optimus cards
# Description:       Daemon responsible for handling power management for
#                    nVidia Optimus cards and handling optirun requests which
#                    allows the discrete card to be used
### END INIT INFO

PATH=/sbin:/usr/sbin:/bin:/usr/bin
NAME=bumblebeed
DAEMON=/usr/sbin/$NAME
DAEMON_ARGS="--daemon --use-syslog"
PIDFILE=/var/run/$NAME.pid
SCRIPTFILE=/etc/init.d/$NAME
DESC="Bumblebee daemon"

. /lib/lsb/init-functions

do_start()
{
	# Return
	#   0 if daemon has been started
	#   1 if daemon was already running
	#   2 if daemon could not be started
	start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON --test > /dev/null \
	 || return 1
	start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON -- \
	 $DAEMON_ARGS \
	 || return 2
}

do_stop()
{
	# Return
	#   0 if daemon has been stopped
	#   1 if daemon was already stopped
	#   2 if daemon could not be stopped
	#   other if a failure occurred
	start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PIDFILE --name $NAME
	return $?
}

case "$1" in
  start)
	log_daemon_msg "Starting $DESC" "$NAME"
	do_start
	case "$?" in
	  0|1) log_end_msg 0 ;;
	  2) log_end_msg 1 ;;
	esac
	;;
  stop)
	log_daemon_msg "Stopping $DESC" "$NAME"
	do_stop
	case "$?" in
	  0|1) log_end_msg 0 ;;
	  2) log_end_msg 1 ;;
	esac
	;;
  status)
	status_of_proc "$DAEMON" "$NAME" && exit 0 || exit $?
	;;
  restart|force-reload)
	log_daemon_msg "Restarting $DESC" "$NAME"
	do_stop
	case "$?" in
	  0|1)
		do_start
		case "$?" in
		  0) log_end_msg 0 ;;
		  1) log_end_msg 1 ;; # Old process is still running
		  *) log_end_msg 1 ;; # Failed to start
		esac
		;;
	  *)
		# Failed to stop
		log_end_msg 1
		;;
	esac
	;;
  *)
	echo "Usage: $SCRIPTNAME {start|stop|status|restart|force-reload}" >&2
	exit 3
	;;
esac
