#!/bin/sh
### BEGIN INIT INFO
# Provides:          ifupdown-clean
# Required-Start:    mountdevsubfs hostname
# Required-Stop:     
# Default-Start:     S
# Default-Stop:
# Short-Description: Clean old interface status info during boot.
### END INIT INFO

set -e

. /lib/lsb/init-functions

MYNAME="${0##*/}"
PATH=/sbin:/bin
[ -r /etc/default/ifupdown ] && . /etc/default/ifupdown

# Note: The state file location is hardcoded in ifup|ifdown
# it is used as a variable in this script order to ease transitions
# to other locations by the package (not by the sysadmin), if you want
# to setup an alternate location please use a symlink
IFSTATE=/etc/network/run/ifstate

case "$1" in
  start)
    log_begin_msg "Cleaning up ifupdown..."
    if [ -f $IFSTATE -a ! -L $IFSTATE ]; then
      rm -f "$IFSTATE"
    elif [ -f $IFSTATE ]; then
      # This is kinda bad :(
      >$IFSTATE
    fi
    log_end_msg 0
    exit 0
    ;;

  stop|restart|force-reload)
    exit 0
    ;;

  *)
    echo "Usage: $0 {start|stop|restart|force-reload}" >&2
    exit 3
    ;;
esac

