#!/bin/sh

## live-boot contains the scripts that configure a Debian Live system during
## the boot process (early userspace).
##
## This is the sysvinit script for live-boot.


### BEGIN INIT INFO
# Provides:		live
# Required-Start:	$syslog bootmisc
# Required-Stop:
# Should-Start:		$local_fs
# Should-Stop:		halt reboot
# Default-Start:	S
# Default-Stop:		0 6
# Short-Description:	Debian Live - System Configuration Scripts
# Description:		live-boot contains the scripts that configure a Debian
#			Live system during the boot process (early userspace).
# X-Start-Before:
# X-Stop-After:		umountroot
# X-Interactive:	true
### END INIT INFO

case "${1}" in
	stop)
		if [ -e /lib/live/boot-init.sh ]
		then
			/lib/live/boot-init.sh ${@}
		fi
		;;

	start|force-reload|restart)

		;;
esac
