#!/bin/sh

## live-config contains the scripts that configure a Debian Live system during
## the boot process (late userspace).
##
## This is the sysvinit script for live-config.


### BEGIN INIT INFO
# Provides:		live-config
# Required-Start:
# Required-Stop:
# Should-Start:
# Should-Stop:
# Default-Start:	S
# Default-Stop:
# Short-Description:	Debian Live - System Configuration Scripts
# Description:		live-config contains the scripts that configure a Debian
#			Live system during the boot process (late userspace).
# X-Start-Before:
# X-Stop-After:
# X-Interactive:	true
### END INIT INFO

case "${1}" in
	start)
		/lib/live/config.sh
		;;

	force-reload|restart|stop)

		;;
esac
