#!/bin/bash

test -d /tmp || mkdir /tmp
chmod 1777 /tmp

mount -o remount,noexec /tmp &>/dev/null && exit 0

test -e /tmp.img || {
	dd if=/dev/zero of=/tmp.img seek=256M count=0 bs=1
	mke2fs -F /tmp.img
}

modprobe loop

mount -t ext2 -o loop,noexec,noatime /tmp.img /tmp
chmod 1777 /tmp
u="/tmp/.X11-unix"
test -d $u || mkdir $u
chown root:root $u
chmod 1777 $u
