#!/bin/bash

# Author: rufo <rufo@rufoa.com>
# See https://bugs.debian.org/855868

if [ -n "$(gpgconf --list-options gpg-agent | \
            awk -F: '/^enable-ssh-support:/{ print $10 }')" ]; then
    echo SSH_AUTH_SOCK=$(gpgconf --list-dirs agent-ssh-socket)
    echo GSM_SKIP_SSH_AGENT_WORKAROUND=true
fi
