#!/bin/sh -e
#
# udev script for alsa-utils

(
	. /lib/udev/hotplug.functions
	wait_for_file /usr/sbin/alsactl
	DEV_BASENAME="${DEVNAME##*/}"
	N="${DEV_BASENAME#controlC}"
	exec /etc/init.d/alsa-utils start $N
) &

