#!/bin/sh

exec >&3

echo "-- initramfs sizes"
ls -lh /boot/initrd.img-2.6.*

echo "-- /proc/cmdline"
cat /proc/cmdline
echo

if [ -r  /etc/initramfs-tools/conf.d/resume ]; then
	echo "-- resume"
	cat  /etc/initramfs-tools/conf.d/resume
fi

echo "-- /proc/filesystems"
grep -v nodev /proc/filesystems
echo

echo "-- lsmod"
lsmod
echo

if [ -r /etc/initramfs-tools/modules ]; then
	echo "-- /etc/initramfs-tools/modules"
	sed 's/#.*$//;/^[[:space:]]*$/d' /etc/initramfs-tools/modules
	echo
fi

if [ -r /etc/kernel-img.conf ]; then
	echo "-- /etc/kernel-img.conf"
	cat /etc/kernel-img.conf
	echo
fi

if [ -r /etc/initramfs-tools/initramfs.conf ]; then
	echo "-- /etc/initramfs-tools/initramfs.conf"
	sed 's/#.*$//;/^[[:space:]]*$/d' /etc/initramfs-tools/initramfs.conf
	echo
fi

if [ -r /etc/initramfs-tools/update-initramfs.conf ]; then
	echo "-- /etc/initramfs-tools/update-initramfs.conf"
	sed 's/#.*$//;/^[[:space:]]*$/d' /etc/initramfs-tools/update-initramfs.conf
	echo
fi

if [ -r /etc/crypttab ]; then
	echo "-- /etc/crypttab"
	cat /etc/crypttab
	echo
fi

if [ -r /proc/mdstat ]; then
	echo "-- /proc/mdstat"
	cat /proc/mdstat
	echo
fi

if grep -rq "MODULES=dep" /etc/initramfs-tools/ ; then
	echo "-- /sys/block"
	ls /sys/block
	echo
fi

echo "-- mkinitramfs hooks"
ls /usr/share/initramfs-tools/hooks /etc/initramfs-tools/hooks/
echo
