#!/bin/sh
#
# Author: Petter Reinholdtsen
# Date: 2009-08-04
#
# Transition script only to be used by sysv-rc version 2.87dsf-2 if
# insserv is upgraded without sysv-rc being upgraded too.

set -e

case "$1" in
    enable|'')
	exit 0
	;;
    check)
	exit 1
	;;
    *)
	echo "error: Unknown argument '$1'"
	exit 1
	;;
esac

exit 0
