#!/usr/bin/perl -w

use strict;
use Debian::DictionariesCommon q(:all);

dico_checkroot ();

my $cachedir   = "/var/cache/dictionaries-common";
my $class      = "aspell";
my %locales    = ();

updatedb ($class);
build_emacsen_support ();
build_squirrelmail_support ();
# 
build_jed_support ();

# Clean orphaned remove files and its contents.
my $dictionaries = loaddb ($class);
dico_clean_orphaned_removefiles($class,$dictionaries);

system ("aspell-autobuildhash") == 0
    or die "Error running aspell-autobuildhash\n";
#

__END__

=head1 NAME

update-dictcommon-aspell - rebuild aspell database and emacsen stuff

=head1 SYNOPSIS

 update-dictcommon-aspell

=head1 DESCRIPTION

WARNING: Not to be used from the command line unless you know very well what you are doing.

This script, when called from aspell dict package postinst or postrm will
rebuild aspell database as well as squirrelmail, jed and emacsen stuff.

=head1 SEE ALSO

The dictionaries-common policy

=head1 AUTHORS

Rafael Laboissiere,
Agustin Martin

=cut
