#!/bin/sh
. /etc/webc/webc.conf
server="http://ping.webconverger.org/"
sleeping=5

ping () {
	logger "Pinging $server"
	wget -qO- --timeout=5 --post-data="M=$( 
		mac_address | md5sum | awk '{print $1}'
	)&V=${webc_version}" $server 
}

while true
do
	if ping "$i"
	then
		logger "Successful ping to $server"
		exit
	fi

	logger "Failed to ping $server, sleeping $sleeping seconds"
	sleep $sleeping

done &
