#!/bin/sh
. /etc/webc/webc.conf
server="http://ping.webconverger.org/"
sleeping=5

webcping () {
	logger "Pinging $server"
	wget -qO- --timeout=5 --post-data="M=$( 
		mac_address | md5sum | awk '{print $1}'
	)&V=${webc_version}" $server 
}

runonce=/var/run/webcping

if test -f /var/lock/webcping
then
	logger webcping already running
	exit 1
fi

while ! test -f $runonce
do
	touch /var/lock/webcping
	if webcping
	then
		logger "Successful ping to $server"
		date > $runonce
		exit
	fi

	logger "Failed to ping $server, sleeping $sleeping seconds"
	sleep $sleeping

done &

