#!/bin/sh

## live-config(7) - System Configuration Components
## Copyright (C) 2006-2015 Daniel Baumann <mail@daniel-baumann.ch>
## Copyright (C) 2016 Raphael Hertzog <hertzog@debian.org>
##
## This program comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
## This is free software, and you are welcome to redistribute it
## under certain conditions; see COPYING for details.

set -e

SYSTEMD_DIR=$1

. /lib/live/init-config.sh

Cmdline ()
{
	# Reading kernel command line
	for _PARAMETER in $(cat /proc/cmdline)
	do
		case "${_PARAMETER}" in
			live-config.debug|debug)
				LIVE_CONFIG_DEBUG="true"
				;;

			live-config.noautologin|noautologin)
				LIVE_CONFIG_NOAUTOLOGIN="true"
				;;

			live-config.nottyautologin|nottyautologin)
				LIVE_CONFIG_NOTTYAUTOLOGIN="true"
				;;

			live-config.username=*|username=*)
				LIVE_USERNAME="${_PARAMETER#*username=}"
				;;
		esac
	done
}

Init ()
{
	# Do nothing if not booted in live mode
	if ! grep -q "boot=live" /proc/cmdline
	then
		exit 0
	fi

	# Disables both console and graphical autologin.
	case "${LIVE_CONFIG_NOAUTOLOGIN}" in
		true)
			exit 0
			;;
	esac

	# Disables console autologin, no matter what mechanism
	case "${LIVE_CONFIG_NOTTYAUTOLOGIN}" in
		true)
			exit 0
			;;
	esac

	# Check if configuration already happened
	if [ -e $SYSTEMD_DIR/getty@tty1.service.d/live-config_autologin.conf ]
	then
		exit 0
	fi
}

Config ()
{
	# Configure autologin
	if [ -n "${LIVE_USERNAME}" ]
	then
		for NUMBER in $(seq 1 6)
		do
			GETTY_SERVICE_D=$SYSTEMD_DIR/getty@tty${NUMBER}.service.d
			CONF=$GETTY_SERVICE_D/live-config_autologin.conf
			mkdir -p $GETTY_SERVICE_D

			cat > $CONF << EOF
[Service]
Type=idle
ExecStart=
ExecStart=-/sbin/agetty --autologin ${LIVE_USERNAME} --noclear %I \$TERM
EOF

			if [ "${LIVE_CONFIG_DEBUG}" = "true" ]
			then
				echo "TTYVTDisallocate=no" >> $CONF
			fi
		done
	fi
}

Cmdline
Init
Config

exit 0
