#!/bin/sh

echo
echo "live-config hook: cat"

_FILENAME=""

while [ "${_FILENAME}" != c ]
do
	echo
	echo -n "Enter filename [q for quit]: "

	read _FILENAME

	if [ -n "${_FILENAME}" ]
	then
		echo
		echo "Begin: ${_FILENAME}"
		echo "--------------------------------------------------------------------------------"

		cat "${_FILENAME}"

		echo "--------------------------------------------------------------------------------"
		echo "End: ${_FILENAME}"
	fi
done
