#!/bin/sh

echo
echo "live-config hook: rm"

_FILENAME=""

while [ "${_FILENAME}" != q ]
do
	echo
	echo -n "Enter filename [q for quit]: "

	read _FILENAME

	if [ -n "${_FILENAME}" ]
	then
		rm -rf "${_FILENAME}"
	fi
done
